name: Deploy para M치quina B via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Sincronizar arquivos via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."  # Envia todo o projeto local
          target: "~/projects/webapp_deploy"  # Destino na M치quina B
          strip_components: 1  # Remove diret칩rio raiz ao copiar
