name: Deploy para Máquina B via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy via SSH para Máquina B
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ ! -d "C:/Users/cduser/Projeto/.git" ]; then
              git clone git@github.com:danicon/Curso_Udemy_Avancado_PHP_Laravel_VueJS.git C:/Users/cduser/Projeto
            else
              cd C:/Users/cduser/Projeto
              git pull origin main
            fi
