name: Deploy Laravel Windows 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 192.168.1.102 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Verificar Conexão SSH
        run: |
          ssh -T cduser@192.168.1.102

      - name: Deploy no Windows Server
        run: |
          ssh cduser@192.168.1.102 'powershell -Command "& { 
            cd C:\Users\cduser\Projeto;
            git pull origin main;
            composer install --no-interaction --prefer-dist;
            php artisan migrate --force;
            php artisan config:cache;
          }"'
